# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 311c8603d8bfb364e24faa7428c7fc1fab55b050d0a041afffed9cb66af2e7268b94c246ad6eedb7ed79147c954b91ffc62e7ce4652d7bb215453f93c61be88c

test:
  secret_key_base: 77ecb1c2e8171a5fd826c40dde6276218f49aace6932d95acd1062acddaafab0cc7383b89ff0679bf7c435bc5f5740ec7989576c6de42d684e8a5b45b2299fb8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
