system:
  title: 'DROP検索'
  url: 'https://drop-search.herokuapp.com/'
  bbs_url: 'http://newburu.main.jp/bbs/drop-search/joyful.cgi'
  description: '必要なアイテムから狩場を決める際の参考に！'
  twitter_site: newburu
  twitter:
    url: 'https://twitter.com/'
    tweet_url: 'http://twitter.com/intent/tweet?'
    share_url: 'http://twitter.com/share?'
  portal:
    limit: 10
  image:
    thumbnail:
      size: "52x75"
  send_dm:
    timing: [0,1,3,5,10]
